# Generated by Django 2.2.1 on 2019-09-30 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tblID', models.PositiveIntegerField()),
                ('date', models.DateField(null=True)),
                ('totalGame', models.PositiveIntegerField()),
                ('playerNum', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TblMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('dispName', models.CharField(blank=True, default='', max_length=20)),
                ('inputName1', models.CharField(blank=True, default='', max_length=20)),
                ('inputName2', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TblScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameNo', models.PositiveIntegerField(null=True)),
                ('gamePt', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('row', models.PositiveIntegerField(default=0, null=True)),
                ('serve1st', models.BooleanField(default=False, null=True)),
                ('serve2nd', models.NullBooleanField()),
                ('serveTurn', models.PositiveIntegerField(default=0, null=True)),
                ('temp', models.BooleanField(default=False, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='score.TblDaily')),
                ('pairID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pair_Member', to='score.TblMember')),
                ('playerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_Member', to='score.TblMember')),
            ],
        ),
        migrations.CreateModel(
            name='TblRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameNum', models.PositiveIntegerField()),
                ('gamePt', models.FloatField()),
                ('gross', models.FloatField()),
                ('HDCP', models.FloatField()),
                ('net', models.FloatField()),
                ('winNum', models.PositiveIntegerField()),
                ('playerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='score.TblMember')),
            ],
        ),
    ]
