# Generated by Django 2.2.1 on 2019-10-01 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tblID', models.IntegerField()),
                ('thresholdPtn', models.CharField(blank=True, default='', max_length=50)),
                ('dispTblName', models.CharField(blank=True, default='', max_length=50)),
                ('startPeriod', models.DateField(null=True)),
                ('endPeriod', models.DateField(null=True)),
                ('hideLastMonth', models.BooleanField(default=False)),
                ('rvNum', models.IntegerField()),
                ('chNum', models.IntegerField()),
                ('event1name', models.CharField(blank=True, default='', max_length=50)),
                ('event2name', models.CharField(blank=True, default='', max_length=50)),
                ('event3name', models.CharField(blank=True, default='', max_length=50)),
                ('event4name', models.CharField(blank=True, default='', max_length=50)),
                ('event5name', models.CharField(blank=True, default='', max_length=50)),
                ('event6name', models.CharField(blank=True, default='', max_length=50)),
                ('event7name', models.CharField(blank=True, default='', max_length=50)),
                ('event8name', models.CharField(blank=True, default='', max_length=50)),
                ('comment', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TblPeriodData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HDCP', models.FloatField(null=True)),
                ('event1', models.IntegerField(null=True)),
                ('event2', models.IntegerField(null=True)),
                ('event3', models.IntegerField(null=True)),
                ('event4', models.IntegerField(null=True)),
                ('event5', models.IntegerField(null=True)),
                ('event6', models.IntegerField(null=True)),
                ('event7', models.IntegerField(null=True)),
                ('event8', models.IntegerField(null=True)),
                ('adjustDate', models.IntegerField(null=True)),
                ('playerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='score.TblMember')),
                ('tblID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.TblManage')),
            ],
        ),
    ]
